services:
  keycloak:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=keycloak
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

  config-server:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=config-server
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  discovery-server:
#    volumes:
#      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
#      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
#    environment:
#      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
#      - OTEL_SERVICE_NAME=discovery-server
#      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
#      - OTEL_METRICS_EXPORTER=none
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  api-gateway:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=api-gateway
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

  student-service:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=student-service
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

  subject-service:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=subject-service
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-service:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=user-service
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"

  codelist-service:
    volumes:
      - "./otel/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar"
      - "./otel/digma-otel-agent-extension.jar:/otel/digma-otel-agent-extension.jar"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://host.docker.internal:5050 -Dotel.javaagent.extensions=/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc
      - OTEL_SERVICE_NAME=codelist-service
      - OTEL_RESOURCE_ATTRIBUTES=digma.environment=IS-STAG
      - OTEL_METRICS_EXPORTER=none
    extra_hosts:
      - "host.docker.internal:host-gateway"