services:
  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    command: start-dev --import-realm
    volumes:
      - /Users/kuba/Downloads/realm-export.json:/opt/keycloak/data/import/realm.json