database:
    credentials:
        username: ENC[AES256_GCM,data:BSjzFqDNTw==,iv:xscAJL+MhmppmdnnwnuHApTwa5jg03Zbu6QRJ1AlT20=,tag:jlTjUI0grf81m8pFoej3xA==,type:str]
        password: ENC[AES256_GCM,data:ZmtyWg==,iv:7mD8hkTmryE2wrEjT0GiIlSOVgf19xvKhxJPTeC2B3o=,tag:t5GOkxzKVlDNbyezi7CDKw==,type:str]
        proxy:
            username: ENC[AES256_GCM,data:nDzyAVG1wbNJDW4=,iv:QKdZDUzgiNBg7IzsyWUMkhJ7mQbbatUtKit05hXeB1w=,tag:SbCGoDoP+1d9RKn6ekEsjw==,type:str]
            password: ENC[AES256_GCM,data:8kKQnw==,iv:n4QMhxKo7Z4BQYEEQGmeXTqL9V1WgR7s6gAaI1d55KA=,tag:X9kw2OYxlPkYS2OSojjU7g==,type:str]
            targetUsername: ENC[AES256_GCM,data:2trQWlr20R8=,iv:mkb5C8zpMefmyG4j12NIjEUl2WHZlk9Mq6ygpxHpIM0=,tag:6ORrKCkQbnQlE2peo1YI6A==,type:str]
redis:
    credentials:
        password: ENC[AES256_GCM,data:vpmbZkU=,iv:Z1ZtdZrey9r+d5h8fI2MG26Eu347VKAfI9WFgjwRrLI=,tag:ZrOjUm3T08s9HckF45SPDQ==,type:str]
sops:
    age:
        - recipient: age1g0tt02e6duuerd5wkakkcw03ng5yunhnh6ms0mj3908fwn0qx9lqlwzdx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYUh5Nnd3RThSWDV2SUVy
            ejh0elZBbjBiRlpFYy9QWlpSRkpqRDJjRGtjCnlEaUdaSzFjYmdFMEtlTjE3RHVP
            UkFQWGdYVG5aS2xOOXhLWWJzTjJSMzAKLS0tIDBQWDN1SSs2Q0xPd0hBYXFId3Q0
            V2w4U3ZiYTVZeVVIcTNVOUlHTllwNWMKdyEIp1gsA30u4PJyeJf3yOg/VCqU2ITb
            BwmKsVxJllMX2zA8KO4ZE3Ws7rLf/vn41H93w9qEQgJ4IN+eKSnR9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T08:30:15Z"
    mac: ENC[AES256_GCM,data:tnlWRkVE++r7Jk56N4ILAnS/dH93neXB5mwN+IpX3tEIhzl7Ffau+wrARQu61rn9BYWkuHtUGfjrRR7H1jDZ/qqAqwP1qyxEQfI2Y++EOwXYo4qwlit2psI7LGKz8WnhXSJSmGfiy+4Hp3yqqmuToyMifFLANYJmCCFCFzfNaEs=,iv:4RE3ES5FB0exPsFyn0EUl+s/xbwLuHdEGBYk5SAmXiM=,tag:IJOPVj0pS5PNX5uFhgI+MQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
