/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/students/{studentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get student
     * @description Retrieve a student by their unique identifier.
     *
     *     **Required Roles:**
     *     * `AD`, `DE`, `PR`, `SR`, `SP`, `VY`, `VK`
     *     * `ST` (only if accessing their own data)
     */
    get: operations['getStudentProfile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Student ID
     * @description The unique alphanumeric identifier for a student.
     * @example K24B4302P
     */
    StudentId: string
    /**
     * Person ID
     * Format: int32
     * @description Unique identifier of the person.
     * @example 221264
     */
    PersonId: number
    /**
     * Student Response
     * @description Response containing student details.
     */
    StudentResponse: {
      studentId: components['schemas']['StudentId']
      personId: components['schemas']['PersonId']
      /**
       * @description First name of the student.
       * @example John
       */
      firstName: string
      /**
       * @description Last name of the student.
       * @example Doe
       */
      lastName: string
      titles: components['schemas']['Titles']
      /**
       * @description Gender of the student.
       * @example male
       */
      gender: string
      studyProgram: components['schemas']['StudyProgram']
      fieldOfStudy: components['schemas']['FieldOfStudy']
    }
    /**
     * Titles
     * @description Academic titles associated with the student (prefix and suffix).
     */
    Titles: {
      prefix: components['schemas']['Title']
      suffix: components['schemas']['Title']
    }
    /**
     * @description An academic title, such as 'Ing.' or 'Ph.D.'.
     * @example Ing.
     */
    Title: string | null
    /**
     * Study Program
     * @description Object containing student's study program details.
     */
    StudyProgram: {
      /**
       * Format: int32
       * @description Unique identifier of the study program.
       * @example 1966
       */
      id: number
      /**
       * @description Name of the study program.
       * @example Ekonomická a regionální geografie
       */
      name: string
      /**
       * @description Faculty of the study program.
       * @example FEK
       */
      faculty: string
      /**
       * @description Code of the study program.
       * @example B0532A330036
       */
      code: string | null
      /**
       * @description Form of the study program.
       * @example Prezenční
       */
      form: string
      /**
       * @description Type of the study program.
       * @example Bakalářský
       */
      type: string
    }
    /**
     * Field Of Study
     * @description Object containing student's field of study details.
     */
    FieldOfStudy: {
      /**
       * Format: int32
       * @description Unique identifier of the field of study.
       * @example 4343
       */
      id: number
      /**
       * @description Name of the field of study.
       * @example Ekonomická a regionální geografie
       */
      name: string
      /**
       * @description Faculty of the field of study.
       * @example FEK
       */
      faculty: string
      /**
       * @description Department of the field of study.
       * @example KGE
       */
      department: string | null
      /**
       * @description Code of the field of study.
       * @example B0532A330036
       */
      code: string
    }
    /**
     * Problem Detail
     * @description A generic error, as defined by RFC 7807. It can be extended with additional properties.
     */
    ProblemDetail: {
      /**
       * Format: uri
       * @description A URI reference that identifies the problem type.
       * @example http://localhost:8080/student-not-found
       */
      type: string
      /**
       * @description A short, human-readable summary of the problem type.
       * @example Student Not Found
       */
      title: string
      /**
       * Format: int32
       * @description The HTTP status code.
       * @example 404
       */
      status: number
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Student with ID: K24B4302P not found
       */
      detail: string
      /**
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example /students/K24B4302P
       */
      instance: string
    } & {
      [key: string]: unknown
    }
  }
  responses: {
    /** @description Bad request. */
    '400BadRequest': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/bad-request",
         *       "title": "Bad Request",
         *       "status": 400,
         *       "detail": "Invalid student ID",
         *       "instance": "/api/v1/students/-10"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description Access token is missing or invalid. */
    '401Unauthorized': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/unauthorized",
         *       "title": "Unauthorized",
         *       "status": 401,
         *       "detail": "Access token is missing or invalid",
         *       "instance": "/api/v1/students/K24B4302P"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description You do not have permission to access this resource. */
    '403Forbidden': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/forbidden",
         *       "title": "Forbidden",
         *       "status": 403,
         *       "detail": "You do not have permission to access this resource",
         *       "instance": "/api/v1/students/K24B4302P"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description The specified resource was not found. */
    '404NotFound': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/student-not-found",
         *       "title": "Student Not Found",
         *       "status": 404,
         *       "detail": "Student with ID: 221264 not found",
         *       "instance": "/api/v1/students/K24B4302P"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description Internal server error. */
    '500InternalServerError': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/internal-server-error",
         *       "title": "Internal server error",
         *       "status": 500,
         *       "detail": "An unexpected error occurred",
         *       "instance": "/api/v1/students/K24B4302P"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description The service is currently unavailable. */
    '503ServiceUnavailable': {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "http://localhost:8080/api/v1/service-unavailable",
         *       "title": "Service Unavailable",
         *       "status": 503,
         *       "detail": "Service is currently unavailable. Please try again later.",
         *       "instance": "/api/v1/students/K24B4302P"
         *     }
         */
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
    /** @description Unexpected error. */
    Default: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['ProblemDetail']
      }
    }
  }
  parameters: {
    /** @description Preferred language */
    AcceptLanguage: 'cs' | 'en'
    /** @description The unique identifier of the student to retrieve. */
    StudentId: components['schemas']['StudentId']
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getStudentProfile: {
    parameters: {
      query?: never
      header?: {
        /** @description Preferred language */
        'Accept-Language'?: components['parameters']['AcceptLanguage']
      }
      path: {
        /** @description The unique identifier of the student to retrieve. */
        studentId: components['parameters']['StudentId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Student details retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StudentResponse']
        }
      }
      400: components['responses']['400BadRequest']
      401: components['responses']['401Unauthorized']
      403: components['responses']['403Forbidden']
      404: components['responses']['404NotFound']
      500: components['responses']['500InternalServerError']
      503: components['responses']['503ServiceUnavailable']
      default: components['responses']['Default']
    }
  }
}
