server:
  port: 8761
  http2:
    enabled: true
  compression:
    enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    response-cache-update-interval-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: discovery-server
  threads:
    virtual:
      enabled: true