spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  server:
    response-cache-update-interval-ms: 10000

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888
