server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://localhost:8180/realms/is-stag/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: student-service
              uri: http://student-service:8030
              predicates:
                - Path=/students/**
            - id: user-service
              uri: http://student-service:8020
              predicates:
                - Path=/users/**,/api/v1/persons/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/