server:
  port: 8100
  http2:
    enabled: true
  ssl:
    key-store: classpath:gateway-keystore.p12
    key-store-type: PKCS12
    key-store-password: ${API_GATEWAY_SSL_KEY_STORE_PASSWORD}
    key-alias: api-gateway

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://keycloak:8080/realms/is-stag/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      cache:
        ttl: 15s
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          routes:
            # Service routes
            - id: codelist-service
              uri: lb://codelist-service
              predicates:
                - Path=/api/v1/codelists/**
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/v1/students/**
            - id: study-plan-service
              uri: lb://study-plan-service
              predicates:
                - Path=/api/v1/study-plan/**
            - id: subject-service
              uri: lb://subject-service
              predicates:
                - Path=/api/v1/subjects/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/persons/**

            # OpenAPI routes for aggregation
            - id: codelist-service-openapi
              uri: lb://codelist-service
              predicates:
                - Path=/codelist-service/**
              filters:
                - RewritePath=/codelist-service/openapi.yaml, /openapi.yaml
            - id: student-service-openapi
              uri: lb://student-service
              predicates:
                - Path=/student-service/**
              filters:
                - RewritePath=/student-service/openapi.yaml, /openapi.yaml
            - id: study-plan-service-openapi
              uri: lb://study-plan-service
              predicates:
                - Path=/study-plan-service/**
              filters:
                - RewritePath=/student-service/openapi.yaml, /openapi.yaml
            - id: subject-service-openapi
              uri: lb://subject-service
              predicates:
                - Path=/subject-service/**
              filters:
                - RewritePath=/subject-service/openapi.yaml, /openapi.yaml
            - id: user-service-openapi
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - RewritePath=/user-service/openapi.yaml, /openapi.yaml
  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Codelist Service
        url: /codelist-service/openapi.yaml
      - name: Student Service
        url: /student-service/openapi.yaml
      - name: Study Plan Service
        url: /study-plan-service/openapi.yaml
      - name: Subject Service
        url: /subject-service/openapi.yaml
      - name: User Service
        url: /user-service/openapi.yaml
  api-docs:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    # Reduce service discovery delays
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Cache registry locally to avoid repeated lookups
    registry-fetch-interval-seconds: 10
    cache-refresh-executor-thread-pool-size: 2
    initial-instance-info-replication-interval-seconds: 10

---

spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/is-stag/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
