server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://keycloak:8080/realms/is-stag/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/students/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**,/api/v1/persons/**

eureka:
  instance:
    prefer-ip-address: true
    # Reduce service discovery delays
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Cache registry locally to avoid repeated lookups
    registry-fetch-interval-seconds: 10
    cache-refresh-executor-thread-pool-size: 2
    initial-instance-info-replication-interval-seconds: 10