server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://localhost:8180/realms/is-stag/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/v1/students/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/persons/**
  threads:
    virtual:
      enabled: true

otel:
  instrumentation:
    kafka:
      enabled: false
    mongo:
      enabled: false
    r2dbc:
      enabled: false
  traces:
    exporter: otlp
    sampler: parentbased_traceidratio
    sampler.arg: 1
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://otel:4318
      protocol: http/protobuf

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/