server:
  port: 8010

grpc:
  server:
    port: 9010

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: none
      default_schema: ${spring.datasource.hikari.schema}
    open-in-view: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=atreus.zcu.cz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=pelops.zcu.cz)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DEMO_SERVICE)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))
    username: install
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      schema: install2
      auto-commit: false
      minimum-idle: 10                   # Keep 5 connections ready at all times.
      maximum-pool-size: 20              # Max number of connections. Tune based on the load.
      idle-timeout: 600000               # 10 minutes. Connections won't be closed before this.
      connection-timeout: 30000          # 30 seconds. How long to wait for a connection.
      max-lifetime: 1800000              # 30 minutes. Max lifetime of a connection.
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: LOCAL

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    url: openapi.yaml