server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  threads:
    virtual:
      enabled: true

otel:
  traces:
    exporter: otlp
    sampler: parentbased_traceidratio
    sampler.arg: 1
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://otel:4318
      protocol: http/protobuf