server:
  port: 8040

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=atreus.zcu.cz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=pelops.zcu.cz)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DEMO_SERVICE)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))
    username: install
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: LOCAL
  threads:
    virtual:
      enabled: true

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    url: openapi.yaml