server:
  port: 8020

grpc:
  server:
    port: 9020
  client:
    student-service:
      address: discovery:///student-service
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
      idle-timeout: 60s
      max-inbound-message-size: 4MB
      max-outbound-message-size: 4MB
      channel-shutdown-timeout: 5s
      enable-retry: true
      max-retry-attempts: 3
      retry-delay: 100ms
    codelist-service:
      address: discovery:///codelist-service
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
      idle-timeout: 60s
      max-inbound-message-size: 4MB
      max-outbound-message-size: 4MB
      channel-shutdown-timeout: 5s
      enable-retry: true
      max-retry-attempts: 3
      retry-delay: 100ms

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=atreus.zcu.cz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=pelops.zcu.cz)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DEMO_SERVICE)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))
    username: install
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: LOCAL
            implicitStatementCacheSize: 200
  threads:
    virtual:
      enabled: true

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    # Reduce service discovery delays
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Cache registry locally to avoid repeated lookups
    registry-fetch-interval-seconds: 10
    cache-refresh-executor-thread-pool-size: 2
    initial-instance-info-replication-interval-seconds: 10

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    url: openapi.yaml