apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
  namespace: is-stag
  labels:
    app: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      name: react-client
      namespace: is-stag
      labels:
        app: react-client
    spec:
      containers:
        - name: react-client
          image: jakubpavlicek/react-client:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: react-client
  namespace: is-stag
spec:
  selector:
    app: react-client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP