apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelist-service
  labels:
    app: codelist-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codelist-service
  template:
    metadata:
      name: codelist-service
      labels:
        app: codelist-service
    spec:
      containers:
        - name: codelist-service
          image: jakubpavlicek/codelist-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: is-stag-database-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: is-stag-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: is-stag-database-secret
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: codelist-service
spec:
  selector:
    app: codelist-service
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
    - protocol: TCP
      port: 9010
      targetPort: 9010
  type: ClusterIP
