apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-plan-service
  labels:
    app: study-plan-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: study-plan-service
  template:
    metadata:
      name: study-plan-service
      labels:
        app: study-plan-service
    spec:
      containers:
        - name: study-plan-service
          image: jakubpavlicek/study-plan-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
              protocol: TCP
            - containerPort: 9050
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: is-stag-database-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: is-stag-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: is-stag-database-secret
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: study-plan-service
spec:
  selector:
    app: study-plan-service
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
    - protocol: TCP
      port: 9050
      targetPort: 9050
  type: ClusterIP
