auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    min_ready_duration: 1s

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /var/loki

schema_config:
  configs:
    - from: 2025-10-25
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /var/loki/chunks