receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/collector:
    config:
      scrape_configs:
        # This job scrapes the collector's own metrics
        - job_name: opentelemetry-collector
          scrape_interval: 15s
          static_configs:
            - targets: [ "127.0.0.1:8888" ]

processors:
  batch:
  # see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060
  tail_sampling:
    policies: [
      {
        name: filter_url_path,
        type: string_attribute,
        string_attribute: {
          key: url.path,
          values: [ /actuator.*, /swagger-ui.*, /v3/api-docs.* ],
          enabled_regex_matching: true,
          invert_match: true
        }
      }
    ]

exporters:
  otlphttp/traces:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  otlphttp/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/ready"

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch, tail_sampling ]
      exporters: [ otlphttp/traces ]
    metrics:
      receivers: [ otlp, prometheus/collector ]
      processors: [ batch ]
      exporters: [ otlphttp/metrics ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/logs ]