/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/persons/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get person
         * @description Retrieve a person by their unique identifier.
         *
         *     **Required Roles:**
         *     * `AD`, `DE`, `PR`, `SR`, `SP`, `VY`, `VK`
         *     * `ST` (only if accessing their own data)
         */
        get: operations["getPersonProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update person
         * @description Update a person by their unique identifier.
         */
        patch: operations["updatePersonProfile"];
        trace?: never;
    };
    "/persons/{personId}/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get person addresses
         * @description Retrieve addresses associated with a person by their unique identifier.
         *
         *     **Required Roles:**
         *     * `AD`, `DE`, `PR`, `SR`, `SP`, `VY`, `VK`
         *     * `ST` (only if accessing their own data)
         */
        get: operations["getPersonAddresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons/{personId}/banking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get person banking information
         * @description Retrieve banking information associated with a person by their unique identifier.
         *
         *     **Required Roles:**
         *     * `AD`, `DE`, `PR`, `SR`, `SP`, `VY`, `VK`
         *     * `ST` (only if accessing their own data)
         */
        get: operations["getPersonBanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/persons/{personId}/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get person education information
         * @description Retrieve education information associated with a person by their unique identifier.
         *
         *     **Required Roles:**
         *     * `AD`, `DE`, `PR`, `SR`, `SP`, `VY`, `VK`
         *     * `ST` (only if accessing their own data)
         */
        get: operations["getPersonEducation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Person ID
         * Format: int32
         * @description The unique numeric identifier for a person.
         * @example 221264
         */
        PersonId: number;
        /**
         * Student ID
         * @description The unique alphanumeric identifier for a student.
         * @example K24B4302P
         */
        StudentId: string;
        /**
         * Update Person Request
         * @description Request containing person details to be updated.
         */
        UpdatePersonRequest: {
            birthSurname?: components["schemas"]["PersonResponse"]["birthSurname"];
            maritalStatus?: components["schemas"]["PersonResponse"]["maritalStatus"];
            contact?: components["schemas"]["ContactUpdate"];
            titles?: components["schemas"]["TitlesUpdate"];
            birthPlace?: components["schemas"]["BirthPlaceUpdate"];
            bankAccount?: components["schemas"]["BankAccountUpdate"];
        };
        /**
         * Birth Place Update
         * @description Object containing birth place to be updated.
         */
        BirthPlaceUpdate: {
            country?: components["schemas"]["BirthPlace"]["country"];
            city?: components["schemas"]["BirthPlace"]["city"];
        } | null;
        /**
         * Titles Update
         * @description Object containing titles to be updated.
         */
        TitlesUpdate: {
            prefix?: components["schemas"]["Title"];
            suffix?: components["schemas"]["Title"];
        } | null;
        /**
         * Contact Update
         * @description Object containing contact details to be updated.
         */
        ContactUpdate: {
            email?: components["schemas"]["Contact"]["email"];
            phone?: components["schemas"]["Contact"]["phone"];
            mobile?: components["schemas"]["Contact"]["mobile"];
            dataBox?: components["schemas"]["Contact"]["dataBox"];
        } | null;
        /**
         * Bank Account Update
         * @description Object containing bank account details to be updated.
         */
        BankAccountUpdate: {
            accountNumberPrefix?: components["schemas"]["BankAccount"]["accountNumberPrefix"];
            accountNumberSuffix?: components["schemas"]["BankAccount"]["accountNumberSuffix"];
            bankCode?: components["schemas"]["BankAccount"]["bankCode"];
            holderName?: components["schemas"]["BankAccount"]["holderName"];
            holderAddress?: components["schemas"]["BankAccount"]["holderAddress"];
        } | null;
        /**
         * Person Response
         * @description Response containing person details.
         */
        PersonResponse: {
            personId: components["schemas"]["PersonId"];
            /**
             * @description List of student ids associated with the person.
             * @example [
             *       "K24B4302P"
             *     ]
             */
            studentIds: components["schemas"]["StudentId"][];
            /**
             * @description First name of the person.
             * @example John
             */
            firstName: string;
            /**
             * @description Last name of the person.
             * @example Doe
             */
            lastName: string;
            /**
             * Birth Surname
             * @description Birth surname of the person.
             * @example Smith
             */
            birthSurname: string | null;
            contact: components["schemas"]["Contact"];
            titles: components["schemas"]["Titles"];
            /**
             * @description Birth number of the person.
             * @example 7061030163
             */
            birthNumber: string;
            /**
             * Format: date
             * @description Birth date of the person.
             * @example 1990-01-01
             */
            birthDate: string;
            birthPlace: components["schemas"]["BirthPlace"];
            citizenship: components["schemas"]["Citizenship"];
            /**
             * @description Passport number of the person.
             * @example 16128791799
             */
            passportNumber: string | null;
            /**
             * @description Gender of the person.
             * @example male
             */
            gender: string;
            /**
             * Marital Status
             * @description Marital status of the person.
             * @example single
             */
            maritalStatus: string | null;
        };
        /**
         * Citizenship
         * @description Citizenship details of the person.
         */
        Citizenship: {
            /**
             * @description Country of citizenship.
             * @example Czech Republic
             */
            country: string;
            /**
             * @description Citizenship qualifier of the person.
             * @example Občan
             */
            qualifier: string | null;
        };
        /**
         * Birth Place
         * @description Birth place of the person.
         */
        BirthPlace: {
            /**
             * Country
             * @description Birth country of the person.
             * @example Czech Republic
             */
            country: string;
            /**
             * City
             * @description Birth city of the person.
             * @example Prague
             */
            city: string | null;
        };
        /**
         * Titles
         * @description Titles of the person.
         */
        Titles: {
            prefix: components["schemas"]["Title"];
            suffix: components["schemas"]["Title"];
        };
        /**
         * @description Title of the person.
         * @example Ing.
         */
        Title: string | null;
        /**
         * Contact
         * @description Contact information of the person.
         */
        Contact: {
            /**
             * Email
             * Format: email
             * @description Email address of the person.
             * @example Martin95043186@xxx.cz
             */
            email: string | null;
            /**
             * Phone
             * @description Phone number of the person.
             * @example +420123456789
             */
            phone: string | null;
            /**
             * Mobile
             * @description Mobile number of the person.
             * @example +420987654321
             */
            mobile: string | null;
            /**
             * Data Box
             * @description Data box number of the person.
             * @example krmm7m5
             */
            dataBox: string | null;
        };
        /**
         * Address
         * @description Address details of the person.
         */
        Address: {
            /**
             * Street
             * @description Street name of the address.
             * @example Příchovice
             */
            street: string | null;
            /**
             * Street Number
             * @description Street number of the address.
             * @example 97
             */
            streetNumber: string | null;
            /**
             * Zip Code
             * @description Zip code of the address.
             * @example 34901
             */
            zipCode: string | null;
            /**
             * Municipality
             * @description Municipality of the address.
             * @example Stříbro
             */
            municipality: string | null;
            /**
             * Municipality Part
             * @description Part of the municipality.
             * @example Stříbro I
             */
            municipalityPart: string | null;
            /**
             * District
             * @description District of the address.
             * @example Tachov
             */
            district: string | null;
            /**
             * Country
             * @description Country of the address.
             * @example Česká republika
             */
            country: string | null;
        };
        /**
         * Foreign Address
         * @description Address details of the person when they have a foreign residence.
         */
        ForeignAddress: {
            /**
             * Zip Code
             * @description Zip code of the foreign address.
             * @example 1110
             */
            zipCode: string | null;
            /**
             * Municipality
             * @description Municipality of the foreign address.
             * @example Mornaguia
             */
            municipality: string | null;
            /**
             * District
             * @description District of the foreign address.
             * @example manouba
             */
            district: string | null;
            /**
             * Post Office
             * @description Post office of the foreign address.
             * @example Mornaguia
             */
            postOffice: string | null;
        };
        /**
         * Person Addresses Response
         * @description Response containing person addresses.
         */
        AddressesResponse: {
            permanentAddress: components["schemas"]["Address"];
            temporaryAddress: components["schemas"]["Address"];
            foreignPermanentAddress: components["schemas"]["ForeignAddress"];
            foreignTemporaryAddress: components["schemas"]["ForeignAddress"];
        };
        /**
         * Bank Account
         * @description Response containing bank account details.
         */
        BankAccount: {
            /**
             * Account Number Prefix
             * @description Prefix of the bank account number.
             * @example 295538
             */
            accountNumberPrefix: string | null;
            /**
             * Account Number Suffix
             * @description Main part of the bank account number.
             * @example 4167197191
             */
            accountNumberSuffix: string | null;
            /**
             * Bank Code
             * @description Bank code of the bank where the account is held.
             * @example 0100
             */
            bankCode: string | null;
            /**
             * Bank Name
             * @description Name of the bank where the account is held.
             * @example Česká spořitelna, a.s.
             */
            bankName: string | null;
            /**
             * IBAN
             * @description International Bank Account Number (IBAN).
             * @example CZ6508000000002000145399
             */
            iban: string | null;
            /**
             * Currency
             * @description Currency of the bank account.
             * @example CZK
             */
            currency: string | null;
            /**
             * Holder Name
             * @description Name of the account holder.
             * @example Jan Novák
             */
            holderName: string | null;
            /**
             * Holder Address
             * @description Address of the account holder.
             * @example Příchovice 97, 34901 Stříbro, Česká republika
             */
            holderAddress: string | null;
        };
        /**
         * Euro Bank Account
         * @description Bank account details for Euro transactions.
         * @example {
         *       "accountNumberPrefix": "295538",
         *       "accountNumberSuffix": "4167197191",
         *       "bankCode": "0100",
         *       "bankName": "Česká spořitelna, a.s.",
         *       "iban": "CZ6508000000002000145399",
         *       "currency": "EUR",
         *       "holderName": "Jan Novák",
         *       "holderAddress": "Příchovice 97, 34901 Stříbro, Česká republika",
         *       "country": "Česká republika",
         *       "swiftCode": "KOMBCZPPXXX"
         *     }
         */
        EuroBankAccount: components["schemas"]["BankAccount"] & components["schemas"]["CountryAndSwiftCode"];
        /**
         * Country And Swift Code
         * @description Country and SWIFT code of the bank for Euro transactions.
         */
        CountryAndSwiftCode: {
            /**
             * @description Country code of the Euro account.
             * @example Česká republika
             */
            country: string | null;
            /**
             * @description SWIFT code of the bank for Euro transactions.
             * @example KOMBCZPPXXX
             */
            swiftCode: string | null;
        };
        /**
         * Bank Accounts Response
         * @description Bank accounts of the person.
         */
        BankAccountsResponse: {
            account: components["schemas"]["BankAccount"];
            euroAccount: components["schemas"]["EuroBankAccount"];
        };
        /**
         * High School Address
         * @description High School address details.
         */
        HighSchoolAddress: {
            /**
             * @description Street name of the high school address.
             * @example Příchovice
             */
            street: string | null;
            /**
             * @description Zip code of the high school address.
             * @example 34901
             */
            zipCode: string | null;
            /**
             * @description Municipality of the high school address.
             * @example Stříbro
             */
            municipality: string | null;
            /**
             * @description District of the high school address.
             * @example Tachov
             */
            district: string | null;
            /**
             * @description Country of the high school address.
             * @example Česká republika
             */
            country: string | null;
        };
        /**
         * Education Response
         * @description Education details of the person.
         */
        EducationResponse: {
            highSchool: components["schemas"]["HighSchool"];
            foreignHighSchool: components["schemas"]["ForeignHighSchool"];
        };
        /**
         * High School
         * @description Details of the high school attended by the person.
         */
        HighSchool: {
            /**
             * @description Name of the high school.
             * @example Gymnázium
             */
            schoolName: string | null;
            /**
             * @description Field of study at the high school.
             * @example Výpočetní technika a informatika
             */
            fieldOfStudy: string | null;
            /**
             * Format: date
             * @description Date of graduation from the educational institution.
             * @example 2020-06-15
             */
            graduationDate: string | null;
            address: components["schemas"]["HighSchoolAddress"];
        };
        /**
         * Foreign High School
         * @description Details of the foreign high school attended by the person.
         */
        ForeignHighSchool: {
            /**
             * @description Name of the foreign high school.
             * @example International School
             */
            schoolName: string | null;
            /**
             * @description Field of study at the foreign high school.
             * @example Computer Science
             */
            fieldOfStudy: string | null;
            /**
             * @description Location of the foreign high school.
             * @example Paris
             */
            location: string | null;
        };
        /**
         * Problem Detail
         * @description A generic error, as defined by RFC 7807. It can be extended with additional properties.
         */
        ProblemDetail: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             * @example http://localhost:8080/person-not-found
             */
            type: string;
            /**
             * @description A short, human-readable summary of the problem type.
             * @example Domain Not Found
             */
            title: string;
            /**
             * Format: int32
             * @description The HTTP status code.
             * @example 404
             */
            status: number;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Person with ID: 221264 not found
             */
            detail: string;
            /**
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example /persons/221264
             */
            instance: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Bad request. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/bad-request",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "Invalid person ID",
                 *       "instance": "/api/v1/persons/-10"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Access token is missing or invalid. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Access token is missing or invalid",
                 *       "instance": "/api/v1/persons/221264"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description You do not have permission to access this resource. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "You do not have permission to access this resource",
                 *       "instance": "/api/v1/persons/221264"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The specified resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/person-not-found",
                 *       "title": "Person Not Found",
                 *       "status": 404,
                 *       "detail": "Person with ID: 221264 not found",
                 *       "instance": "/api/v1/persons/221264"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Internal server error. */
        "500InternalServerError": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/internal-server-error",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred",
                 *       "instance": "/api/v1/persons/221264"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The service is currently unavailable. */
        "503ServiceUnavailable": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/service-unavailable",
                 *       "title": "Service Unavailable",
                 *       "status": 503,
                 *       "detail": "Service is currently unavailable. Please try again later.",
                 *       "instance": "/api/v1/persons/221264"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected error. */
        Default: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /** @description Preferred language */
        AcceptLanguage: "cs" | "en";
        /** @description Unique identifier of the person. */
        PersonId: components["schemas"]["PersonId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPersonProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                /** @description Unique identifier of the person. */
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            503: components["responses"]["503ServiceUnavailable"];
            default: components["responses"]["Default"];
        };
    };
    updatePersonProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the person. */
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        /** @description Person details to be updated. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description Person details updated successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            503: components["responses"]["503ServiceUnavailable"];
            default: components["responses"]["Default"];
        };
    };
    getPersonAddresses: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                /** @description Unique identifier of the person. */
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person addresses retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressesResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            503: components["responses"]["503ServiceUnavailable"];
            default: components["responses"]["Default"];
        };
    };
    getPersonBanking: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                /** @description Unique identifier of the person. */
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person banking information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccountsResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            503: components["responses"]["503ServiceUnavailable"];
            default: components["responses"]["Default"];
        };
    };
    getPersonEducation: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                /** @description Unique identifier of the person. */
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person education information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EducationResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            503: components["responses"]["503ServiceUnavailable"];
            default: components["responses"]["Default"];
        };
    };
}
