apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: is-stag-ingress
  namespace: is-stag
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: is-stag.cz
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: react-client
                port:
                  number: 5173
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 8100
          - path: /realms/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
