apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: is-stag-ingress
  namespace: is-stag
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - is-stag.cz
      secretName: selfsigned-cert-tls
  rules:
    - host: is-stag.cz
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak-keycloakx-http
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8100
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-client
                port:
                  number: 5173

# TODO: Add Keycloak to cluster
# TODO: Add Grafana to cluster and ingress