fullnameOverride: keycloak

image:
  repository: docker.io/jakubpavlicek/is-stag-keycloak
  tag: latest

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--import-realm"

# Additional init containers, e. g. for providing custom themes
extraInitContainers: ""

http:
  relativePath: /auth

service:
  httpPort: 8080

proxy:
  enabled: false

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: keycloak-postgresql
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-postgresql-secret
  existingSecretKey: postgresql-user-password

extraEnv: |
  # Keycloak admin credentials
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: admin
  
  # Tells Keycloak it’s behind a reverse proxy (Ingress)
  - name: KC_PROXY
    value: "edge"
  
  # Tells Keycloak to trust the X-Forwarded-* headers
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  
  # The public hostname users will use to access Keycloak
  - name: KC_HOSTNAME
    value: "is-stag.cz"

  # Ensures Keycloak generates HTTPS URLs even if backend traffic is HTTP
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  
  # OpenTelemetry Tracing
  - name: KC_TRACING_ENABLED
    value: "true"
  - name: KC_TRACING_ENDPOINT
    value: "http://otel-collector:4317"
  - name: KC_TRACING_PROTOCOL
    value: "grpc"
  - name: KC_TRACING_COMPRESSION
    value: "gzip"
  - name: KC_TRACING_SERVICE_NAME
    value: "keycloak"
  - name: KC_TRACING_RESOURCE_ATTRIBUTES
    value: "service.name=keycloak,service.version=latest,environment=prod,k8s.namespace.name=is-stag"
  - name: KC_TRACING_SAMPLER_TYPE
    value: "parentbased_traceidratio"
  - name: KC_TRACING_SAMPLER_RATIO
    value: "1.0"