loki:
  auth_enabled: false

  ingester:
    lifecycler:
      min_ready_duration: 1s

  commonConfig:
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
    replication_factor: 1
    path_prefix: /var/loki

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2025-10-25
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

test:
  enabled: false

lokiCanary:
  enabled: false