apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: is-stag
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus/collector:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: [ '0.0.0.0:8888' ]

    processors:
      batch: { }
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      # see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060
      tail_sampling:
        policies: [
          {
            name: filter_url_path,
            type: string_attribute,
            string_attribute: {
              key: url.path,
              values: [ /actuator.*, /swagger-ui.*, /v3/api-docs.* ],
              enabled_regex_matching: true,
              invert_match: true
            }
          }
        ]

    exporters:
      debug: { }
      otlphttp/traces:
        endpoint: http://tempo:4318
        tls:
          insecure: true
      otlphttp/metrics:
        endpoint: http://prometheus:9090/api/v1/otlp
        tls:
          insecure: true
      otlphttp/logs:
        endpoint: http://loki:3100/otlp
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: "/ready"

    service:
      extensions: [ health_check ]
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch, tail_sampling ]
          exporters: [ debug, otlphttp/traces ]
        metrics:
          receivers: [ otlp, prometheus/collector ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug, otlphttp/metrics ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug, otlphttp/logs ]