server:
  port: 8100
  http2:
    enabled: true
  compression:
    enabled: true
  ssl:
    key-store: classpath:gateway-keystore.p12
    key-store-type: PKCS12
    key-store-password: ${API_GATEWAY_SSL_KEY_STORE_PASSWORD}
    key-alias: api-gateway

# Templates for API Gateway filters
filter-templates:
  circuitbreaker_args: &circuitbreaker_args
    fallbackUri: forward:/fallback

  retry_args: &retry_args
    retries: 3
    methods: GET, PATCH
    statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://keycloak:8080/realms/is-stag/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      cache:
        ttl: 15s
    gateway:
      server:
        webmvc:
          routes:
            # Service routes
            - id: codelist-service
              uri: lb://codelist-service
              predicates:
                - Path=/api/v1/addresses/**,/api/v1/countries/**,/api/v1/domains/**
              filters:
                - RemoveRequestHeader=Authorization
                - name: CircuitBreaker
                  args:
                    <<: *circuitbreaker_args
                    id: codelist-service
                - name: Retry
                  args:
                    <<: *retry_args
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/v1/students/**
              filters:
                - name: CircuitBreaker
                  args:
                    <<: *circuitbreaker_args
                    id: student-service
                - name: Retry
                  args:
                    <<: *retry_args
            - id: study-plan-service
              uri: lb://study-plan-service
              predicates:
                - Path=/api/v1/study-plan/**
              filters:
                - name: CircuitBreaker
                  args:
                    <<: *circuitbreaker_args
                    id: study-plan-service
                - name: Retry
                  args:
                    <<: *retry_args
            - id: subject-service
              uri: lb://subject-service
              predicates:
                - Path=/api/v1/subjects/**
              filters:
                - name: CircuitBreaker
                  args:
                    <<: *circuitbreaker_args
                    id: subject-service
                - name: Retry
                  args:
                    <<: *retry_args
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/persons/**
              filters:
                - name: CircuitBreaker
                  args:
                    <<: *circuitbreaker_args
                    id: user-service
                - name: Retry
                  args:
                    <<: *retry_args

            # OpenAPI routes for aggregation
            - id: codelist-service-openapi
              uri: lb://codelist-service
              predicates:
                - Path=/codelist-service/**
              filters:
                - RewritePath=/codelist-service/openapi.yaml, /openapi.yaml
            - id: student-service-openapi
              uri: lb://student-service
              predicates:
                - Path=/student-service/**
              filters:
                - RewritePath=/student-service/openapi.yaml, /openapi.yaml
            - id: study-plan-service-openapi
              uri: lb://study-plan-service
              predicates:
                - Path=/study-plan-service/**
              filters:
                - RewritePath=/study-plan-service/openapi.yaml, /openapi.yaml
            - id: subject-service-openapi
              uri: lb://subject-service
              predicates:
                - Path=/subject-service/**
              filters:
                - RewritePath=/subject-service/openapi.yaml, /openapi.yaml
            - id: user-service-openapi
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - RewritePath=/user-service/openapi.yaml, /openapi.yaml
  http:
    client:
      read-timeout: 10s
      connect-timeout: 10s
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 20
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 10s
        register-health-indicator: true
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 75
    instances:
      codelist-service:
        base-config: default
      student-service:
        base-config: default
      study-plan-service:
        base-config: default
      subject-service:
        base-config: default
      user-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: true

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Codelist Service
        url: /codelist-service/openapi.yaml
      - name: Student Service
        url: /student-service/openapi.yaml
      - name: Study Plan Service
        url: /study-plan-service/openapi.yaml
      - name: Subject Service
        url: /subject-service/openapi.yaml
      - name: User Service
        url: /user-service/openapi.yaml
  api-docs:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    # Reduce service discovery delays
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Cache registry locally to avoid repeated lookups
    registry-fetch-interval-seconds: 10
    cache-refresh-executor-thread-pool-size: 2
    initial-instance-info-replication-interval-seconds: 10

---

spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/is-stag/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
