server:
  port: 8030
  http2:
    enabled: true
  compression:
    enabled: true

grpc:
  server:
    port: 9030
  client:
    user-service:
      address: discovery:///user-service
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
      max-inbound-message-size: 4MB
    study-plan-service:
      address: discovery:///study-plan-service
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 5s
      max-inbound-message-size: 4MB

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/is-stag
          jwk-set-uri: http://keycloak:8080/realms/is-stag/protocol/openid-connect/certs
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
        jdbc:
          fetch_size: 50
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=atreus.zcu.cz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=pelops.zcu.cz)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DEMO_SERVICE)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))
    username: install
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: LOCAL
            implicitStatementCacheSize: 200
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes
      cache-null-values: false
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 20
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count-based
        sliding-window-size: 100
        wait-duration-in-open-state: 10s
        register-health-indicator: true
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 75
    instances:
      user-service:
        base-config: default
      study-plan-service:
        base-config: default
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        enable-randomized-wait: true
        retry-exceptions:
          - io.grpc.StatusRuntimeException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      user-service:
        base-config: default
      study-plan-service:
        base-config: default

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    # Reduce service discovery delays
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Cache registry locally to avoid repeated lookups
    registry-fetch-interval-seconds: 10
    cache-refresh-executor-thread-pool-size: 2
    initial-instance-info-replication-interval-seconds: 10

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml

---

spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/is-stag/protocol/openid-connect/certs
  data:
    redis:
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
