server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JakubPavlicek/is-stag
          default-label: master
          search-paths: config
