server:
  port: 8040
  http2:
    enabled: true
  compression:
    enabled: true

#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: DEBUG

spring:
  application:
    name: subject-service
  jackson:
    mapper:
      sort-properties-alphabetically: false
  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        generate_statistics: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
        jdbc:
          fetch_size: 50
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=atreus.zcu.cz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=pelops.zcu.cz)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DEMO_SERVICE)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=180)(DELAY=5))))
    username: install
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: LOCAL
            implicitStatementCacheSize: 200
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes
      cache-null-values: false
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml