apiVersion: v2
name: generic-service
description: A generic Helm chart for deploying an IS/STAG service
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Jakub Pavlíček
    email: jpvlck@students.zcu.cz