openapi: 3.0.3
info:
  title: Codelist Service API
  description: |
    This API provides access to various code lists, also known as dictionaries or enumerations, which are fundamental for the IS/STAG system.
  version: 1.0.0
  contact:
    name: STAG Support
    email: stag@service.zcu.cz
    url: https://is-stag.zcu.cz/zakaznici/Support.html

servers:
  - url: /api/v1
    description: Codelist Service API through API Gateway

tags:
  - name: countries
    description: Operations for managing countries
  - name: domains
    description: Operations for managing codelist domains

paths:

  /countries:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - countries
      summary: Get all countries
      description: Retrieve list of all countries available in the system.
      operationId: getCountries
      parameters:
        - $ref: '#/components/parameters/AcceptLanguage'
      responses:
        '200':
          description: List of available countries.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

  /domains:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - domains
      summary: Get all codelist domains
      description: Retrieve list of all domains available in the code lists system.
      operationId: getCodeListDomains
      responses:
        '200':
          description: List of available domains.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        'default':
          $ref: '#/components/responses/Default'

components:

  securitySchemes:

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Keycloak.

  parameters:

    AcceptLanguage:
      name: Accept-Language
      in: header
      description: Preferred language.
      required: false
      schema:
        type: string
        enum:
          - cs
          - en
        default: cs

  schemas:

    CountryListResponse:
      type: object
      title: Country List Response
      description: Response containing a list of countries.
      additionalProperties: false
      nullable: false
      required:
        - countries
      properties:
        countries:
          type: array
          description: List of countries.
          items:
            $ref: '#/components/schemas/Country'
          minItems: 1
          nullable: false
          uniqueItems: true
          example:
            - id: 203
              name: Czech Republic
              generalName: Czechia
            - id: 204
              name: Slovak Republic
              generalName: Slovakia

    Country:
      type: object
      title: Country
      description: Response containing a country.
      additionalProperties: false
      nullable: false
      required:
        - id
        - name
        - generalName
      properties:
        id:
          type: integer
          format: int32
          nullable: false
          description: Unique identifier of the country.
          example: 203
          minimum: 1
        name:
          type: string
          nullable: false
          description: Name of the country.
          example: Czech Republic
          maxLength: 240
        generalName:
          type: string
          nullable: true
          description: General name of the country.
          example: Czechia
          maxLength: 70

    DomainListResponse:
      type: object
      title: Domain List Response
      description: Response containing a list of codelist domains.
      additionalProperties: false
      nullable: false
      required:
        - domains
      properties:
        domains:
          type: array
          description: List of codelist domains.
          items:
            $ref: '#/components/schemas/Domain'
          minItems: 1
          nullable: false
          uniqueItems: true
      example:
        domains:
          - ADRESA
          - FAKULTA
          - PRACOVISTE

    Domain:
      type: string
      title: Domain
      nullable: false
      description: A codelist domain name.
      example: ADRESA
      minLength: 1
      maxLength: 100

    ProblemDetail:
      type: object
      title: Problem Detail
      description: A generic error.
      additionalProperties: false
      nullable: false
      required:
        - type
        - title
        - status
        - detail
        - instance
      properties:
        type:
          type: string
          format: uri
          nullable: false
          description: A URI reference that identifies the problem type.
          example: "http://localhost:8080/countries"
          pattern: ^((about:blank)|(https?://[^\s]+))$
          maxLength: 1000
        title:
          type: string
          nullable: false
          description: A short, human-readable summary of the problem type.
          example: Internal Server Error
          pattern: ^[A-Za-z0-9\s\-.,!?:;'"]+$
          maxLength: 255
        status:
          type: integer
          format: int32
          nullable: false
          description: The HTTP status code.
          example: 404
        detail:
          type: string
          nullable: false
          description: A human-readable explanation specific to this occurrence of the problem.
          example: An unexpected error occurred
          pattern: ^[A-Za-z0-9\s\-.,!?:;'"]+$
          maxLength: 1000
        instance:
          type: string
          nullable: false
          description: A URI reference that identifies the specific occurrence of the problem.
          example: /countries
          pattern: ^(/[^\s]*)+$
          maxLength: 1000
        contextInfo:
          type: object
          additionalProperties: true
          nullable: false
          maxProperties: 5
          description: A free-form based object that contains additional context about the error.
          example:
            domain: Something went wrong

  responses:

    400BadRequest:
      description: Bad request.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/bad-request
            title: Bad Request
            status: 400
            detail: Invalid Language header
            instance: /api/v1/countries

    401Unauthorized:
      description: Access token is missing or invalid.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/unauthorized
            title: Unauthorized
            status: 401
            detail: Access token is missing or invalid
            instance: /api/v1/countries

    403Forbidden:
      description: You do not have permission to access this resource.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/forbidden
            title: Forbidden
            status: 403
            detail: You do not have permission to access this resource
            instance: /api/v1/countries

    500InternalServerError:
      description: Internal server error.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/internal-server-error
            title: Internal server error
            status: 500
            detail: An unexpected error occurred
            instance: /api/v1/countries

    Default:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'

