openapi: 3.1.0
info:
  title: Code Lists Service API
  description: |
    This API provides access to various code lists, also known as dictionaries or enumerations, which are fundamental for the IS/STAG system.
    It allows for the management and retrieval of data related to university structure, such as faculties and departments (workplaces), as well as time-related data like teaching hours.
  version: 1.0.0
  contact:
    name: STAG Support
    email: stag@service.zcu.cz
    url: https://is-stag.zcu.cz/zakaznici/Support.html

servers:
  - url: /api/v1
    description: Main API server

tags:
  - name: code-lists
    description: Operations for managing code lists (dictionaries)
  - name: workplaces
    description: Operations for managing workplaces
  - name: time-series
    description: Operations for managing time series

paths:
  /code-lists/domains:
    get:
      tags:
        - code-lists
      summary: Get all code list domains
      description: Retrieve list of all domains available in the code lists system.
      operationId: getCodeListDomains
      responses:
        '200':
          description: List of available domains
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainsResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'

components:

  schemas:

    DomainsResponse:
      type: object
      title: Domains Response
      description: Response containing a list of code list domains.
      additionalProperties: false
      required:
        - domains
      properties:
        domains:
          type: array
          items:
            type: string
            description: A code list domain identifier.
            example: ADRESA
          minItems: 1
          uniqueItems: true
      example:
        domains:
          - ADRESA
          - FAKULTA
          - PRACOVISTE

    ProblemDetail:
      type: object
      title: Problem Detail
      description: "A generic error."
      additionalProperties: false
      required:
        - type
        - title
        - status
        - detail
        - instance
      properties:
        type:
          type: string
          description: "A URI reference that identifies the problem type."
          example: "http://localhost:8080/domain-not-found"
          pattern: "^((about:blank)|(https?://[^\\s]+$))"
          maxLength: 1000
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          example: Domain Not Found
          pattern: "^[A-Za-z0-9\\s\\-.,!?:;'\"]+$"
          maxLength: 255
        status:
          type: number
          description: The HTTP status code.
          example: 404
        detail:
          type: string
          description: "A human-readable explanation specific to this occurrence of the problem."
          example: "Domain with ID: TEST not found"
          pattern: "^[A-Za-z0-9\\s\\-.,!?:;'\"]+$"
          maxLength: 1000
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem.
          example: /codelists/TEST
          pattern: "^(/[^\\s]*)+$"
          maxLength: 1000
        contextInfo:
          type: object
          additionalProperties: true
          maxProperties: 5
          description: A free-form based object that contains additional context about the error.
      example:
        type: http://localhost:8080/api/v1/domain-not-found
        title: Domain Not Found
        status: 404
        detail: "Domain with ID: TEST not found"
        instance: /api/v1/codelists/TEST
        contextInfo:
          domain: domain TEST not found

  responses:

    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: http://localhost:8080/api/v1/internal-server-error
            title: Internal server error
            status: 500
            detail: An unexpected error occurred
            instance: /api/v1/codelists/TEST

