/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all countries
         * @description Retrieve list of all countries available in the system.
         *
         *     **Required Roles:** None (Public access)
         */
        get: operations["getCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all domains
         * @description Retrieve list of all domains available in the code lists system.
         *
         *     **Required Roles:** None (Public access)
         */
        get: operations["getDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get domain values
         * @description Retrieve a domain values by its unique identifier.
         *
         *     **Required Roles:** None (Public access)
         */
        get: operations["getDomainValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Country List Response
         * @description Response containing a list of countries.
         */
        CountryListResponse: {
            /**
             * @description List of countries.
             * @example [
             *       {
             *         "id": 203,
             *         "name": "Czech Republic",
             *         "commonName": "Czechia",
             *         "abbreviation": "CZ"
             *       },
             *       {
             *         "id": 204,
             *         "name": "Slovak Republic",
             *         "commonName": "Slovakia",
             *         "abbreviation": "SK"
             *       }
             *     ]
             */
            countries: components["schemas"]["Country"][];
        };
        /**
         * Country
         * @description Response containing a country.
         */
        Country: {
            /**
             * Format: int32
             * @description Unique identifier of the country.
             * @example 203
             */
            id: number;
            /**
             * @description Name of the country.
             * @example Czech Republic
             */
            name: string;
            /**
             * @description Common name of the country.
             * @example Czechia
             */
            commonName: string | null;
            /**
             * @description Abbreviation of the country.
             * @example CZ
             */
            abbreviation: string;
        };
        /**
         * Domain List Response
         * @description Response containing a list of codelist domains.
         * @example {
         *       "domains": [
         *         "TITUL_PRED",
         *         "TITUL_ZA",
         *         "STAV",
         *         "CIS_BANK",
         *         "FAKULTA"
         *       ]
         *     }
         */
        DomainListResponse: {
            /** @description List of codelist domains. */
            domains: components["schemas"]["Domain"][];
        };
        /**
         * Domain
         * @description A domain name.
         * @example FAKULTA
         */
        Domain: string;
        /**
         * Domain Value List Response
         * @description Response containing a list of values belonging to the specified domain.
         */
        DomainValueListResponse: {
            /**
             * @description List of values belonging to the specified domain.
             * @example [
             *       {
             *         "key": "FAV",
             *         "name": "Fakulta aplikovaných věd",
             *         "abbreviation": "FAV"
             *       },
             *       {
             *         "key": "FEL",
             *         "name": "Fakulta elektrotechnická",
             *         "abbreviation": "FEL"
             *       }
             *     ]
             */
            values: components["schemas"]["DomainValue"][];
        };
        /**
         * Domain Value
         * @description Object representing a value belonging to the specified domain.
         */
        DomainValue: {
            /**
             * @description Key of the value.
             * @example FAV
             */
            key: string;
            /**
             * @description Name of the value.
             * @example Fakulta aplikovaných věd
             */
            name: string;
            /**
             * @description Abbreviation of the value.
             * @example FAV
             */
            abbreviation: string | null;
        };
        /**
         * Problem Detail
         * @description A generic error, as defined by RFC 7807. It can be extended with additional properties.
         */
        ProblemDetail: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             * @example http://localhost:8080/countries
             */
            type: string;
            /**
             * @description A short, human-readable summary of the problem type.
             * @example Internal Server Error
             */
            title: string;
            /**
             * Format: int32
             * @description The HTTP status code.
             * @example 404
             */
            status: number;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example An unexpected error occurred
             */
            detail: string;
            /**
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example /countries
             */
            instance: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Bad request. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/bad-request",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "Invalid Language header",
                 *       "instance": "/api/v1/countries"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Access token is missing or invalid. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Access token is missing or invalid",
                 *       "instance": "/api/v1/countries"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description You do not have permission to access this resource. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "You do not have permission to access this resource",
                 *       "instance": "/api/v1/countries"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The specified resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/domain-not-found",
                 *       "title": "Domain Not Found",
                 *       "status": 404,
                 *       "detail": "Domain with ID: STAT not found",
                 *       "instance": "/api/v1/domains/STAT"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Internal server error. */
        "500InternalServerError": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "http://localhost:8080/api/v1/internal-server-error",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred",
                 *       "instance": "/api/v1/countries"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected error. */
        Default: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /** @description Preferred language. */
        AcceptLanguage: "cs" | "en";
        /** @description The unique identifier of the domain to retrieve. */
        Domain: components["schemas"]["Domain"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCountries: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available countries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryListResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            500: components["responses"]["500InternalServerError"];
            default: components["responses"]["Default"];
        };
    };
    getDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available domains. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainListResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            500: components["responses"]["500InternalServerError"];
            default: components["responses"]["Default"];
        };
    };
    getDomainValues: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred language. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                /** @description The unique identifier of the domain to retrieve. */
                domain: components["parameters"]["Domain"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainValueListResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            404: components["responses"]["404NotFound"];
            500: components["responses"]["500InternalServerError"];
            default: components["responses"]["Default"];
        };
    };
}
