name: Build and Publish Docker Images
on:
  push:
    paths:
      - 'services/**'
      - 'client/**'

jobs:
  build-push-services:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: liberica
          java-version: 24.0.2
          cache: maven

      - name: Install mvnd
        run: |
          MVND_VERSION=2.0.0-rc-3
          curl -sL https://downloads.apache.org/maven/mvnd/${MVND_VERSION}/maven-mvnd-${MVND_VERSION}-linux-amd64.zip -o mvnd.zip
          unzip -q mvnd.zip
          echo "$PWD/maven-mvnd-${MVND_VERSION}-linux-amd64/bin" >> $GITHUB_PATH

      - name: Warm Up Dependencies
        run: mvnd -B -T 1C dependency:go-offline

      - name: Build and Push Spring Boot Docker Images
        run: |
          mvnd -B -T 1C -DskipTests spring-boot:build-image \
            -Dspring-boot.build-image.publish=true \
            -Ddocker.username=${{ secrets.DOCKERHUB_USERNAME }} \
            -Ddocker.password=${{ secrets.DOCKERHUB_TOKEN }}

  build-push-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 24.7.0
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Setup Buildpacks Tools
        uses: buildpacks/github-actions/setup-tools@v5.1.0

      - name: Setup Buildpacks Pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      # TODO: Change NODE_ENV to prod

      - name: Build Docker Image with Buildpacks
        run: |
          npm ci
          NAME=$(npm pkg get name | tr -d '"')
          VER=$(npm pkg get version | tr -d '"')
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${NAME}
          pack build ${IMAGE_NAME}:${VER} \
            --builder paketobuildpacks/builder-jammy-base \
            --buildpack paketo-buildpacks/web-servers \
            --env BP_NPM_VERSION=11.5.2 \
            --env BP_NODE_RUN_SCRIPTS=build \
            --env NODE_ENV=dev \
            --env BP_WEB_SERVER=nginx \
            --env BP_WEB_SERVER_ENABLE_PUSH_STATE=true \
            --env BP_WEB_SERVER_ROOT=/workspace/dist \
            --publish
